### ISSUE TITLE
remove separate release notes file?

### ISSUE THREAD

**Issue by aschweigert** [INN/WP-DS-NPR-API#3]
if we have them in the readme we probably shouldn't also have them in a separate file

**Comment by aschweigert** [comment]
@jackbrighton did you just literally copy and paste here or are there any differences between the two versions?

**Comment by jackbrighton** [comment]
There's no difference. The WP validator wanted them in readme.txt so I put them there. Is that incorrect?

**Comment by aschweigert** [comment]
nope, just remove that other file then
