### ISSUE TITLE
update push documentation

### ISSUE THREAD

**Issue by aschweigert** [INN/WP-DS-NPR-API#5]
To cover changes made in https://github.com/INN/WP-DS-NPR-API/commit/7a7ad78d157f67f34a47bc941b136908ad5a58b4

When a post is published it won't automatically get pushed to the API unless the author/editor explicitly chooses to do so (by hitting the "push to API" button

**Comment by aschweigert** [comment]
@rnagle does that meta box/button only appear if the PMP plugin is installed alongside this one? or is it now just the default state?

**Comment by aschweigert** [comment]
the relevant docs are here: https://github.com/INN/WP-DS-NPR-API/blob/master/docs/pushing.md

**Comment by jackbrighton** [comment]
Looks like the Push to NPR meta box/button is dependent only on the NPR API plugin. I disabled the PMP plugin and the push to NPR API is still there.
